# Generated by Django 4.2.4 on 2023-09-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Тема')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
