# Generated by Django 4.2.5 on 2023-09-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='сategory',
            field=models.CharField(default=1, max_length=100, verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
